import { generateSprintHealth } from "./generateSprintHealth.js";


export function buildSummaryBlocks(summaryText,insight) {
  const completed = countItems(summaryText, "Completed work");
  const progress = countItems(summaryText, "In progress");
  const blockers = countItems(summaryText, "Blockers");

  const sprintHealthData = generateSprintHealth(
        completed,
        progress,
        blockers
    );
  return [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: "🚀 Sprint Summary",
      },
    },

    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `Generated by SprintFlow AI • ` +
                `${sprintHealthData.status} • ` +
                `Sprint Health Score: *${sprintHealthData.score}/100*`,
        },
      ],
    },

    {
      type: "section",
      fields: [
        {
          type: "mrkdwn",
          text: `✅ *${completed} Completed*`,
        },
        {
          type: "mrkdwn",
          text: `🛠️ *${progress} Active*`,
        },
        {
          type: "mrkdwn",
          text: `⚠️ *${blockers} Blockers*`,
        },
      ],
    },

    {
      type: "divider",
    },

    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "✅ *Completed work*\n" +
          extractSection(summaryText, "Completed work"),
      },
    },

    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "🛠️ *In progress*\n" +
          extractSection(summaryText, "In progress"),
      },
    },

    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "⚠️ *Blockers*\n" +
          extractSection(summaryText, "Blockers"),
      },
    },

    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "📌 *Next steps*\n" +
          extractSection(summaryText, "Next steps"),
      },
    },

    {
      type: "divider",
    },

    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "🧠 *AI Insight*\n" +
          insight
      },
    },

    {
      type: "divider",
    },

    {
      type: "actions",
      elements: [
        {
          type: "button",
          text: {
            type: "plain_text",
            text: "📌 View Details",
          },
          style: "primary",
          value: "view_details",
          action_id: "view_details",
        },

        {
          type: "button",
          text: {
            type: "plain_text",
            text: "🧠 Generate Risks",
          },
          value: "generate_risks",
          action_id: "generate_risks",
        },

        {
          type: "button",
          text: {
            type: "plain_text",
            text: "📝 Summarize Thread",
          },
          value: "summarize_thread",
          action_id: "summarize_thread",
        },
      ],
    },
  ];
}

function extractSection(text, sectionTitle) {
  const regex = new RegExp(
    `\\*\\*${sectionTitle}\\*\\*([\\s\\S]*?)(?=\\*\\*|$)`,
    "i"
  );

  const match = text.match(regex);

  if (!match) return "_No updates available_";

  return match[1].trim();
}

function countItems(text, sectionTitle) {
  const section = extractSection(text, sectionTitle);

  return (section.match(/•/g) || []).length;
}

// function generateInsight(blockers) {
//   if (blockers >= 3) {
//     return "High blocker count may impact sprint delivery timelines.";
//   }

//   if (blockers >= 1) {
//     return "Current blockers should be monitored closely.";
//   }

//   return "Sprint execution appears stable with low delivery risk.";
// }